DATA:
    ROOT: ''
    TRAIN_FILE: '/data/users/sdas/scripts/ViFi-CLIP/merged_dataset_new.csv'
    VAL_FILE: '/data/users/sdas/scripts/ViFi-CLIP/merged_dataset_new.csv'
    DATASET: kinetics400
    NUM_FRAMES: 16
    NUM_CLASSES: 45
    LABEL_LIST: '/data/users/sdas/scripts/ViFi-CLIP/labels/challenge.csv'
SAVE_FREQ: 30
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 8 # BS 512
    ACCUMULATION_STEPS: 8
    EPOCHS: 30
    LR: 2.2e-05
TEST:
    MULTI_VIEW_INFERENCE: False
    ONLY_TEST: False
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
